server:
  global:
    scrape_interval: 10s
  scrape_configs:
    - job_name: "fastapi"
      static_configs:
        - targets: ["fastapi-backend-service:8000"]

grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

#  ingress:
 #   enabled: true
 #   annotations:
  #    kubernetes.io/ingress.class: "nginx"
   #   cert-manager.io/cluster-issuer: "letsencrypt-prod"  # For HTTPS (if using cert-manager)
  #  hosts:
   #   - grafana.example.com  # Change to your actual domain
    #tls:
     # - hosts:
      #    - grafana.example.com
       # secretName: grafana-tls  # For HTTPS, update accordingly
